[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[build-dependencies]
embuild = "0.31.1"

[dependencies]
esp-idf-hal = { version = "0.40.1" }
esp-idf-svc = { version = "0.45.0" }
esp-idf-sys = { version = "0.32.1", features = ["binstart"] }
